### ISSUE TITLE
R&D Proposal second draft

### ISSUE THREAD

**Issue by mohanrajroboticist** [RnDProjectsDeebul/MohanRajRnD#2]
[Mohan Raj Nadarajan_R&D_Proposal_28_Nov.pdf](https://github.com/RnDProjectsDeebul/MohanRajRnD/files/10107724/Mohan.Raj.Nadarajan_R.D_Proposal_28_Nov.pdf)

**Comment by deebuls** [comment]
[R.D_Proposal_27_Nov_revived.pdf](https://github.com/RnDProjectsDeebul/MohanRajRnD/files/10111338/R.D_Proposal_27_Nov_revived.pdf)
